import 'package:mobile_booking_online_doctor/features/home/data/models/doctor_model.dart';
import 'package:mobile_booking_online_doctor/features/home/data/models/specialty_model.dart';

List<SpecialtyModel> dummySpecialties = [
  SpecialtyModel(
    id: 1,
    nameEn: 'Cardiologist',
    nameAr: 'طب القلب',
    description: 'Specialty focused on heart and cardiovascular system.',
    icon: 'assets/icons/Cardiologist.svg',
  ),
  SpecialtyModel(
    id: 2,
    nameEn: 'Orthopedic',
    nameAr: 'طب العظام',
    description: 'Specialty focused on musculoskeletal system.',
    icon: 'assets/icons/Orthopedic.svg',
  ),
  SpecialtyModel(
    id:   3,
    nameEn: 'Neurologist',
    nameAr: 'طب الأعصاب',
    description: 'Specialty focused on nervous system and brain.',
    icon: 'assets/icons/Neurologist.svg',
  ),
  SpecialtyModel(
    id: 4,
    nameEn: 'Gastroenterologist',
    nameAr: 'طب الجهاز الهضمي',
    description: 'Specialty focused on digestive system and its disorders.',
    icon: 'assets/icons/Gastroenterologist.svg',
  ),
  SpecialtyModel(
    id: 5,
    nameEn: 'Psychiatrist',
    nameAr: 'طب النفس',
    description: 'Specialty focused on mental health and disorders.',
    icon: 'assets/icons/Psychiatrist.svg',
  ),
  SpecialtyModel(
    id: 6,
    nameEn: 'Ophthalmologist',
    nameAr: 'طب العيون',
    description: 'Specialty focused on eye and vision care.',
    icon: 'assets/icons/Ophthalmologist.svg',
  ),
  SpecialtyModel(
    id: 7,
    nameEn: 'Endocrinologist',
    nameAr: 'طب الغدد الصماء',
    description: 'Specialty focused on hormones and endocrine system.',
    icon: 'assets/icons/Endocrinologist.svg',
  ),
  SpecialtyModel(
    id: 8,
    nameEn: 'Pulmonologist',
    nameAr: 'طب الرئة',
    description: 'Specialty focused on respiratory system and lung diseases.',
    icon: 'assets/icons/Pulmonologist.svg',
  ),
  SpecialtyModel(
    id: 9,
    nameEn: 'Oncologist',
    nameAr: 'طب الأورام',
    description: 'Specialty focused on cancer diagnosis and treatment.',
    icon: 'assets/icons/Oncologist.svg',
  ),
  SpecialtyModel(
    id: 10,
    nameEn: 'Dentist',
    nameAr: 'طب الأسنان',
    description: 'Specialty focused on oral health and dental care.',
    icon: 'assets/icons/Dentist.svg',
  ),
  SpecialtyModel(
    id: 11,
    nameEn: 'General Practitioner',
    nameAr: 'الطبيب العام',
    description: 'Specialty focused on general health and primary care.',
    icon: 'assets/icons/General Practitioner.svg',
  ),
  SpecialtyModel(
    id: 12,
    nameEn: 'ENT',
    nameAr: 'طب الأنف والأذن والحنجرة',
    description: 'Specialty focused on ear, nose, and throat disorders.',
    icon: 'assets/icons/ENT.svg',
  ),
];

final List<DoctorModel> doctorsDummyData = [
  // 1 - Cardiologist
  DoctorModel(
    doctorProfileId: 1,
    userId: 1001,
    availabilityId: 2001,
    name: 'Dr. Ahmed Hassan',
    specialtyId: 1,
    specialtyNameEn: 'Cardiologist',
    specialtyNameAr: 'طب القلب',
    specialtyDescription:
    'Specialty focused on heart and cardiovascular system.',
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
    location: 'Cairo, Nasr City',
    rating: '4.8',
    experienceYears: 12,
    pricePerHour: '500 EGP',
    email: 'ahmed.hassan@clinic.com',
    phone: '+201001234567',
    about:
    'Experienced cardiologist specializing in heart failure and hypertension.',
    hospitalId: 1,
    hospitalName: 'Cairo Heart Center',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '05:00 PM',
    day: 'Sunday',
    startTime: '10:00 AM',
    endTime: '02:00 PM',
    availableTime: '10:00 AM - 02:00 PM',
  ),

  // 2 - Cardiologist
  DoctorModel(
    doctorProfileId: 2,
    userId: 1002,
    availabilityId: 2002,
    name: 'Dr. Karim Adel',
    specialtyId: 1,
    specialtyNameEn: 'Cardiologist',
    specialtyNameAr: 'طب القلب',
    specialtyDescription:
    'Specialty focused on heart and cardiovascular system.',
    image: 'https://images.pexels.com/photos/8376290/pexels-photo-8376290.jpeg',
    location: 'Giza, Dokki',
    rating: '4.7',
    experienceYears: 9,
    pricePerHour: '450 EGP',
    email: 'karim.adel@clinic.com',
    phone: '+201112345678',
    about:
    'Focused on early detection of heart diseases and preventive care.',
    hospitalId: 1,
    hospitalName: 'Cairo Heart Center',
    hospitalStartTime: '10:00 AM',
    hospitalEndTime: '06:00 PM',
    day: 'Monday',
    startTime: '01:00 PM',
    endTime: '05:00 PM',
    availableTime: '01:00 PM - 05:00 PM',
  ),

  // 3 - Orthopedic
  DoctorModel(
    doctorProfileId: 3,
    userId: 1003,
    availabilityId: 2003,
    name: 'Dr. Mohamed Ali',
    specialtyId: 2,
    specialtyNameEn: 'Orthopedic',
    specialtyNameAr: 'طب العظام',
    specialtyDescription:
    'Specialty focused on musculoskeletal system.',
    image: 'https://randomuser.me/api/portraits/men/21.jpg',
    location: 'Alexandria, Smouha',
    rating: '4.9',
    experienceYears: 15,
    pricePerHour: '600 EGP',
    email: 'mohamed.ali@clinic.com',
    phone: '+201223456789',
    about:
    'Senior orthopedic surgeon specialized in joint replacement.',
    hospitalId: 2,
    hospitalName: 'Alex Ortho Hospital',
    hospitalStartTime: '08:00 AM',
    hospitalEndTime: '04:00 PM',
    day: 'Wednesday',
    startTime: '09:00 AM',
    endTime: '01:00 PM',
    availableTime: '09:00 AM - 01:00 PM',
  ),

  // 4 - Orthopedic
  DoctorModel(
    doctorProfileId: 4,
    userId: 1004,
    availabilityId: 2004,
    name: 'Dr. Tamer Fathy',
    specialtyId: 2,
    specialtyNameEn: 'Orthopedic',
    specialtyNameAr: 'طب العظام',
    specialtyDescription:
    'Specialty focused on musculoskeletal system.',
    image: 'https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg',
    location: 'Cairo, Heliopolis',
    rating: '4.6',
    experienceYears: 10,
    pricePerHour: '520 EGP',
    email: 'tamer.fathy@clinic.com',
    phone: '+201334567890',
    about:
    'Expert in sports injuries and knee problems.',
    hospitalId: 2,
    hospitalName: 'Ortho Care Clinic',
    hospitalStartTime: '11:00 AM',
    hospitalEndTime: '07:00 PM',
    day: 'Thursday',
    startTime: '02:00 PM',
    endTime: '06:00 PM',
    availableTime: '02:00 PM - 06:00 PM',
  ),

  // 5 - Neurologist
  DoctorModel(
    doctorProfileId: 5,
    userId: 1005,
    availabilityId: 2005,
    name: 'Dr. Sara Mahmoud',
    specialtyId: 3,
    specialtyNameEn: 'Neurologist',
    specialtyNameAr: 'طب الأعصاب',
    specialtyDescription:
    'Specialty focused on nervous system and brain.',
    image: 'https://randomuser.me/api/portraits/women/31.jpg',
    location: 'Cairo, Maadi',
    rating: '4.8',
    experienceYears: 11,
    pricePerHour: '550 EGP',
    email: 'sara.mahmoud@clinic.com',
    phone: '+201445678901',
    about:
    'Specialist in epilepsy and migraine treatment.',
    hospitalId: 3,
    hospitalName: 'Neuro Care Center',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '05:00 PM',
    day: 'Sunday',
    startTime: '11:00 AM',
    endTime: '03:00 PM',
    availableTime: '11:00 AM - 03:00 PM',
  ),

  // 6 - Neurologist
  DoctorModel(
    doctorProfileId: 6,
    userId: 1006,
    availabilityId: 2006,
    name: 'Dr. Hany Samir',
    specialtyId: 3,
    specialtyNameEn: 'Neurologist',
    specialtyNameAr: 'طب الأعصاب',
    specialtyDescription:
    'Specialty focused on nervous system and brain.',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
    location: 'Giza, Mohandessin',
    rating: '4.5',
    experienceYears: 7,
    pricePerHour: '480 EGP',
    email: 'hany.samir@clinic.com',
    phone: '+201556789012',
    about:
    'Focused on nerve disorders and chronic headaches.',
    hospitalId: 3,
    hospitalName: 'Brain Health Clinic',
    hospitalStartTime: '12:00 PM',
    hospitalEndTime: '08:00 PM',
    day: 'Tuesday',
    startTime: '03:00 PM',
    endTime: '07:00 PM',
    availableTime: '03:00 PM - 07:00 PM',
  ),

  // 7 - Gastroenterologist
  DoctorModel(
    doctorProfileId: 7,
    userId: 1007,
    availabilityId: 2007,
    name: 'Dr. Youssef Khaled',
    specialtyId: 4,
    specialtyNameEn: 'Gastroenterologist',
    specialtyNameAr: 'طب الجهاز الهضمي',
    specialtyDescription:
    'Specialty focused on digestive system and its disorders.',
    image: 'https://randomuser.me/api/portraits/men/41.jpg',
    location: 'Cairo, Nasr City',
    rating: '4.7',
    experienceYears: 13,
    pricePerHour: '530 EGP',
    email: 'youssef.khaled@clinic.com',
    phone: '+201667890123',
    about:
    'Expert in liver and digestive diseases.',
    hospitalId: 4,
    hospitalName: 'Digestive Health Center',
    hospitalStartTime: '10:00 AM',
    hospitalEndTime: '06:00 PM',
    day: 'Monday',
    startTime: '12:00 PM',
    endTime: '04:00 PM',
    availableTime: '12:00 PM - 04:00 PM',
  ),

  // 8 - Psychiatrist
  DoctorModel(
    doctorProfileId: 8,
    userId: 1008,
    availabilityId: 2008,
    name: 'Dr. Mona Adel',
    specialtyId: 5,
    specialtyNameEn: 'Psychiatrist',
    specialtyNameAr: 'طب النفس',
    specialtyDescription:
    'Specialty focused on mental health and disorders.',
    image: 'https://randomuser.me/api/portraits/women/51.jpg',
    location: 'Cairo, Zamalek',
    rating: '4.9',
    experienceYears: 14,
    pricePerHour: '600 EGP',
    email: 'mona.adel@clinic.com',
    phone: '+201778901234',
    about:
    'Specialist in anxiety, depression, and stress management.',
    hospitalId: 5,
    hospitalName: 'Mind Care Clinic',
    hospitalStartTime: '01:00 PM',
    hospitalEndTime: '09:00 PM',
    day: 'Thursday',
    startTime: '04:00 PM',
    endTime: '08:00 PM',
    availableTime: '04:00 PM - 08:00 PM',
  ),

  // 9 - Ophthalmologist
  DoctorModel(
    doctorProfileId: 9,
    userId: 1009,
    availabilityId: 2009,
    name: 'Dr. Omar Nabil',
    specialtyId: 6,
    specialtyNameEn: 'Ophthalmologist',
    specialtyNameAr: 'طب العيون',
    specialtyDescription:
    'Specialty focused on eye and vision care.',
    image: 'https://randomuser.me/api/portraits/men/61.jpg',
    location: 'Alexandria, Stanley',
    rating: '4.6',
    experienceYears: 9,
    pricePerHour: '420 EGP',
    email: 'omar.nabil@clinic.com',
    phone: '+201889012345',
    about:
    'Expert in LASIK and vision correction.',
    hospitalId: 6,
    hospitalName: 'Vision Eye Center',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '05:00 PM',
    day: 'Saturday',
    startTime: '10:00 AM',
    endTime: '02:00 PM',
    availableTime: '10:00 AM - 02:00 PM',
  ),

  // 10 - Dentist
  DoctorModel(
    doctorProfileId: 10,
    userId: 1010,
    availabilityId: 2010,
    name: 'Dr. Nada Ibrahim',
    specialtyId: 10,
    specialtyNameEn: 'Dentist',
    specialtyNameAr: 'طب الأسنان',
    specialtyDescription:
    'Specialty focused on oral health and dental care.',
    image: 'https://randomuser.me/api/portraits/women/71.jpg',
    location: 'Cairo, New Cairo',
    rating: '4.8',
    experienceYears: 8,
    pricePerHour: '350 EGP',
    email: 'nada.ibrahim@clinic.com',
    phone: '+201990123456',
    about:
    'Specialist in cosmetic dentistry and teeth whitening.',
    hospitalId: 7,
    hospitalName: 'Smile Dental Clinic',
    hospitalStartTime: '11:00 AM',
    hospitalEndTime: '07:00 PM',
    day: 'Tuesday',
    startTime: '02:00 PM',
    endTime: '06:00 PM',
    availableTime: '02:00 PM - 06:00 PM',
  ),

  // 11 - General Practitioner
  DoctorModel(
    doctorProfileId: 11,
    userId: 1011,
    availabilityId: 2011,
    name: 'Dr. Khaled Mostafa',
    specialtyId: 11,
    specialtyNameEn: 'General Practitioner',
    specialtyNameAr: 'الطبيب العام',
    specialtyDescription:
    'Specialty focused on general health and primary care.',
    image: 'https://randomuser.me/api/portraits/men/81.jpg',
    location: 'Giza, Faisal',
    rating: '4.5',
    experienceYears: 6,
    pricePerHour: '300 EGP',
    email: 'khaled.mostafa@clinic.com',
    phone: '+201223344556',
    about:
    'Primary care physician for adults and children.',
    hospitalId: 8,
    hospitalName: 'Family Health Clinic',
    hospitalStartTime: '08:00 AM',
    hospitalEndTime: '03:00 PM',
    day: 'Sunday',
    startTime: '09:00 AM',
    endTime: '01:00 PM',
    availableTime: '09:00 AM - 01:00 PM',
  ),

  // 12 - ENT
  DoctorModel(
    doctorProfileId: 12,
    userId: 1012,
    availabilityId: 2012,
    name: 'Dr. Amr Salah',
    specialtyId: 12,
    specialtyNameEn: 'ENT',
    specialtyNameAr: 'طب الأنف والأذن والحنجرة',
    specialtyDescription:
    'Specialty focused on ear, nose, and throat disorders.',
    image: 'https://randomuser.me/api/portraits/men/91.jpg',
    location: 'Cairo, Shubra',
    rating: '4.7',
    experienceYears: 10,
    pricePerHour: '450 EGP',
    email: 'amr.salah@clinic.com',
    phone: '+201667788990',
    about:
    'Specialist in sinus and hearing disorders.',
    hospitalId: 9,
    hospitalName: 'ENT Care Center',
    hospitalStartTime: '10:00 AM',
    hospitalEndTime: '06:00 PM',
    day: 'Wednesday',
    startTime: '12:00 PM',
    endTime: '04:00 PM',
    availableTime: '12:00 PM - 04:00 PM',
  ),

  // 13 - Endocrinologist
  DoctorModel(
    doctorProfileId: 13,
    userId: 1013,
    availabilityId: 2013,
    name: 'Dr. Laila Hassan',
    specialtyId: 7,
    specialtyNameEn: 'Endocrinologist',
    specialtyNameAr: 'طب الغدد الصماء',
    specialtyDescription:
    'Specialty focused on hormones and endocrine system.',
    image: 'https://randomuser.me/api/portraits/women/82.jpg',
    location: 'Cairo, Nasr City',
    rating: '4.8',
    experienceYears: 11,
    pricePerHour: '520 EGP',
    email: 'laila.hassan@clinic.com',
    phone: '+201998877665',
    about:
    'Expert in diabetes and thyroid disorders.',
    hospitalId: 10,
    hospitalName: 'Hormone Care Clinic',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '05:00 PM',
    day: 'Monday',
    startTime: '11:00 AM',
    endTime: '03:00 PM',
    availableTime: '11:00 AM - 03:00 PM',
  ),

  // 14 - Pulmonologist
  DoctorModel(
    doctorProfileId: 14,
    userId: 1014,
    availabilityId: 2014,
    name: 'Dr. Sherif Magdy',
    specialtyId: 8,
    specialtyNameEn: 'Pulmonologist',
    specialtyNameAr: 'طب الرئة',
    specialtyDescription:
    'Specialty focused on respiratory system and lung diseases.',
    image: 'https://randomuser.me/api/portraits/men/83.jpg',
    location: 'Giza, Haram',
    rating: '4.6',
    experienceYears: 9,
    pricePerHour: '480 EGP',
    email: 'sherif.magdy@clinic.com',
    phone: '+201776655443',
    about:
    'Specialist in asthma and chronic lung diseases.',
    hospitalId: 11,
    hospitalName: 'Chest Care Center',
    hospitalStartTime: '10:00 AM',
    hospitalEndTime: '06:00 PM',
    day: 'Thursday',
    startTime: '01:00 PM',
    endTime: '05:00 PM',
    availableTime: '01:00 PM - 05:00 PM',
  ),

  // 15 - Oncologist
  DoctorModel(
    doctorProfileId: 15,
    userId: 1015,
    availabilityId: 2015,
    name: 'Dr. Mostafa Nasser',
    specialtyId: 9,
    specialtyNameEn: 'Oncologist',
    specialtyNameAr: 'طب الأورام',
    specialtyDescription:
    'Specialty focused on cancer diagnosis and treatment.',
    image: 'https://randomuser.me/api/portraits/men/84.jpg',
    location: 'Cairo, Ain Shams',
    rating: '4.9',
    experienceYears: 16,
    pricePerHour: '700 EGP',
    email: 'mostafa.nasser@clinic.com',
    phone: '+201665544332',
    about:
    'Senior oncologist with focus on chemotherapy and immunotherapy.',
    hospitalId: 12,
    hospitalName: 'Cancer Care Hospital',
    hospitalStartTime: '08:00 AM',
    hospitalEndTime: '04:00 PM',
    day: 'Sunday',
    startTime: '09:00 AM',
    endTime: '01:00 PM',
    availableTime: '09:00 AM - 01:00 PM',
  ),

  // 16 - Dentist
  DoctorModel(
    doctorProfileId: 16,
    userId: 1016,
    availabilityId: 2016,
    name: 'Dr. Hoda Samy',
    specialtyId: 10,
    specialtyNameEn: 'Dentist',
    specialtyNameAr: 'طب الأسنان',
    specialtyDescription:
    'Specialty focused on oral health and dental care.',
    image: 'https://randomuser.me/api/portraits/women/85.jpg',
    location: 'Alexandria, Gleem',
    rating: '4.7',
    experienceYears: 7,
    pricePerHour: '330 EGP',
    email: 'hoda.samy@clinic.com',
    phone: '+201554433221',
    about:
    'Specialist in pediatric dentistry.',
    hospitalId: 7,
    hospitalName: 'Smile Dental Clinic',
    hospitalStartTime: '12:00 PM',
    hospitalEndTime: '08:00 PM',
    day: 'Wednesday',
    startTime: '03:00 PM',
    endTime: '07:00 PM',
    availableTime: '03:00 PM - 07:00 PM',
  ),

  // 17 - General Practitioner
  DoctorModel(
    doctorProfileId: 17,
    userId: 1017,
    availabilityId: 2017,
    name: 'Dr. Adel Saeed',
    specialtyId: 11,
    specialtyNameEn: 'General Practitioner',
    specialtyNameAr: 'الطبيب العام',
    specialtyDescription:
    'Specialty focused on general health and primary care.',
    image: 'https://randomuser.me/api/portraits/men/86.jpg',
    location: 'Cairo, Imbaba',
    rating: '4.4',
    experienceYears: 5,
    pricePerHour: '280 EGP',
    email: 'adel.saeed@clinic.com',
    phone: '+201443322110',
    about:
    'General physician focused on preventive healthcare.',
    hospitalId: 8,
    hospitalName: 'Family Health Clinic',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '02:00 PM',
    day: 'Monday',
    startTime: '10:00 AM',
    endTime: '01:00 PM',
    availableTime: '10:00 AM - 01:00 PM',
  ),

  // 18 - ENT
  DoctorModel(
    doctorProfileId: 18,
    userId: 1018,
    availabilityId: 2018,
    name: 'Dr. Reham Younes',
    specialtyId: 12,
    specialtyNameEn: 'ENT',
    specialtyNameAr: 'طب الأنف والأذن والحنجرة',
    specialtyDescription:
    'Specialty focused on ear, nose, and throat disorders.',
    image: 'https://randomuser.me/api/portraits/women/87.jpg',
    location: 'Cairo, Abbassia',
    rating: '4.8',
    experienceYears: 12,
    pricePerHour: '480 EGP',
    email: 'reham.younes@clinic.com',
    phone: '+201332211009',
    about:
    'Expert in vocal cord and sinus treatments.',
    hospitalId: 9,
    hospitalName: 'ENT Care Center',
    hospitalStartTime: '11:00 AM',
    hospitalEndTime: '07:00 PM',
    day: 'Thursday',
    startTime: '02:00 PM',
    endTime: '06:00 PM',
    availableTime: '02:00 PM - 06:00 PM',
  ),

  // 19 - Endocrinologist
  DoctorModel(
    doctorProfileId: 19,
    userId: 1019,
    availabilityId: 2019,
    name: 'Dr. Fady George',
    specialtyId: 7,
    specialtyNameEn: 'Endocrinologist',
    specialtyNameAr: 'طب الغدد الصماء',
    specialtyDescription:
    'Specialty focused on hormones and endocrine system.',
    image: 'https://randomuser.me/api/portraits/men/88.jpg',
    location: 'Cairo, Heliopolis',
    rating: '4.6',
    experienceYears: 8,
    pricePerHour: '500 EGP',
    email: 'fady.george@clinic.com',
    phone: '+201221133445',
    about:
    'Focused on hormonal imbalance and metabolic disorders.',
    hospitalId: 10,
    hospitalName: 'Hormone Care Clinic',
    hospitalStartTime: '10:00 AM',
    hospitalEndTime: '06:00 PM',
    day: 'Tuesday',
    startTime: '12:00 PM',
    endTime: '04:00 PM',
    availableTime: '12:00 PM - 04:00 PM',
  ),

  // 20 - Pulmonologist
  DoctorModel(
    doctorProfileId: 20,
    userId: 1020,
    availabilityId: 2020,
    name: 'Dr. Mahmoud Saad',
    specialtyId: 8,
    specialtyNameEn: 'Pulmonologist',
    specialtyNameAr: 'طب الرئة',
    specialtyDescription:
    'Specialty focused on respiratory system and lung diseases.',
    image: 'https://randomuser.me/api/portraits/men/89.jpg',
    location: 'Alexandria, Miami',
    rating: '4.7',
    experienceYears: 10,
    pricePerHour: '490 EGP',
    email: 'mahmoud.saad@clinic.com',
    phone: '+201110022334',
    about:
    'Specialist in COPD and lung infections.',
    hospitalId: 11,
    hospitalName: 'Chest Care Center',
    hospitalStartTime: '09:00 AM',
    hospitalEndTime: '05:00 PM',
    day: 'Saturday',
    startTime: '11:00 AM',
    endTime: '03:00 PM',
    availableTime: '11:00 AM - 03:00 PM',
  ),
];

